### PR TITLE
Update convert_ismapper_to_vcf.py

### PR DESCRIPTION
**Pull request by vrennie**
using Lennert's reformat_lofreq logic to get tbprofiler to read the is mapper vcf

### CODE REVIEW

**Comment by abhi18av** [comment]
Thanks mate!

**Comment by vrennie** [comment]
Hi @abhi18av did you make changes to the container in the past hour or so?

https://cloud.seqera.io/orgs/TORCH/workspaces/XBS-Nextflow/watch/1d87xVDxEv4U0p

**Comment by abhi18av** [comment]
Mmm, seems like when I decremented the `MultiQC` version to `1.22` the `setuptools` package didn't get installed.

I'm building another container containing that package.


I'll trigger the next text on Tower.

References
- https://bobbyhadz.com/blog/python-no-module-named-pkg-resources 
- https://github.com/pre-commit/pre-commit/issues/2122 
-

**Comment by abhi18av** [comment]
Okay, so the `container` issue is now resolved and I think this script introduced a bug since BCFTOOLS is now complaining about the format 

``` 
[W::vcf_parse] Contig 'NC-000962-3-H37Rv' is not defined in the header. (Quick workaround: index the file with tabix.)
[E::vcf_parse_format] Invalid character '.' in 'PL' FORMAT field at NC-000962-3-H37Rv:1591
Error: VCF parse error

```

https://cloud.seqera.io/orgs/TORCH/workspaces/XBS-Nextflow/watch/fqBg3YOWsZf7o

**Comment by vrennie** [comment]
no worries, I will debug! thanks for fixing the container!

**Pull request merged**
