### PR TITLE
Structural variant analysis

### PR DESCRIPTION
**Pull request by abhi18av**
This PR follows up on https://github.com/TORCH-Consortium/MAGMA/issues/146#issuecomment-1495648475

> As part of 4-APR meeting
> 
> - [x] 1. Accommodate another `STRUCTURAL_VARIANTS_ANALYSIS_WF` in the pipeline @abhi18av 
> - [ ] 2. Accommodate them in the `summarize_resistance.py` @LennertVerboven  

Point-1 regarding the subworkflow, has been completed and now the content of `${outdir}/samples/variant_files/structual_variants` is as shown below 

```
structural_variants/
├── delly
└── tbprofiler
``` 

For point-2, over to @LennertVerboven and @vrennie on how to update the python script.

### CODE REVIEW

**Comment by TimHHH** [comment]
This initial step looks pretty good to me.
@LennertVerboven you know a thing or two about reference names in our pipeline, can you confirm that when we run straight on the bam we are not going to run in the issues described here: https://github.com/jodyphelan/TBProfiler#running-with-an-existing-bam-file ?

**Comment by LennertVerboven** [comment]
This needs testing as I am not sure whether we fixed the naming issues in the reference databases TBProfiler uses. But I think we changed the names of the reference genome there to match our pipeline

**Comment by abhi18av** [comment]
Hi team,

Any updates on this one? Perhaps we could now get this done and mention in the manuscript? 

CC @vrennie

**Comment by vrennie** [comment]
Currently waiting for input from Jody

**Comment by LennertVerboven** [comment]
Hi @abhi18av 

I worked on the workflow for the structural variant analysis and it should look like this
# Per sample analysis
```delly call -g NC-000962-3-H37Rv.fa ${sampleName}.dedup_reads.bam -u 30 -o ${sampleName}.delly.bcf
bcftools view -i 'GT="1/1"' ${sampleName}.delly.bcf -o ${sampleName}_filtered.delly.bcf
bcftools index ${sampleName}_filtered.delly.bcf
```

# merge all samples
```
bcftools merge -o ${params.vcf_name}.delly.vcf ${sampleName01}_filtered.delly.bcf ${sampleName02}_filtered.delly.bcf ...
bgzip ${params.vcf_name}.delly.vcf
tb-profiler profile --vcf ${params.vcf_name}.delly.vcf.gz --db who_catalogue_amended_v5.0.0 --dir "${params.outdir}/analyses/drug_resistance/structural_variants/"
```

Could you implement this flow in MAGMA? Beware, the TBProfiler part requires version 5.0.0 of TBProfiler along with a newly generated resistance database which I have available. The 5.0.0 version of TBProfiler has not yet been released, but should be soon. I can send you the database files should you need them (they also need to be loaded with `tb-profiler load_library who_catalogue_amended_v5.0.0`)

**Comment by abhi18av** [comment]
Current status:

- [ ] @abhi18av to prepare the Nextflow codebase to accommodate the updates to `tbprofiler and tbdb` version 
- [ ] @LennertVerboven  `who_catalogue_amended_v5.0.0`  database which needs to be bundled in the pipeline here and rebuild the container
- [ ] @LennertVerboven  to update the `summarise_resistance.py` script
- [ ] ⚠️  @LennertVerboven  `tbprofiler-v5` needs to be released to finalise the branch

**Comment by abhi18av** [comment]
Folks, as this part was blocked https://github.com/TORCH-Consortium/MAGMA/pull/154#issuecomment-1656762457 I disabled the structural variants entirely for the time being https://github.com/TORCH-Consortium/MAGMA/blob/ad887bb8d450483601c93230c9bf123a4af0633d/main.nf#L63

**Comment by LennertVerboven** [comment]
Ill follow up with Jody about the release of V5.0.0

**Comment by LennertVerboven** [comment]
@abhi18av 

TBProfiler V5.0.0 is released and I have created the required resistance databases in the update_tbprofiler_v5 branch, beware the name of the database has changed, but I believe I have updated the nname in all the relevant parts. I have also added another command line argument in the `summarize_resistance.py` script, but it doenst do anythin yet. I will update this when the entire flow works up to that part as that allows for easier testing.

**Comment by abhi18av** [comment]
Thanks @LennertVerboven , further work in this PR would be continued here https://github.com/TORCH-Consortium/MAGMA/pull/169

**Pull request merged**
