### PR TITLE
Improve the structure of results directory

### PR DESCRIPTION
**Pull request by abhi18av**
This PR follows our discussion regarding improvements in the structure of the results directory for `v1.2.0` of the pipeline based on our experience with most frequently accessed/shared files.

**TODO**: Update documentation once the PR has been tested and the structure is confirmed.

### CODE REVIEW

**Comment by abhi18av** [comment]
Okay @mdediegofuertes and @LennertVerboven , so the current top-level directory output looks like this 


image



And here's the current default output 

``` 


├── QC_statistics
│   ├── cohort
│   │   └── multiqc
│   │       └── multiqc_data
│   └── per_sample
│       ├── coverage
│       ├── fastqc
│       └── mapping
├── analyses
│   ├── cluster_analysis
│   ├── drug_resistance
│   │   ├── combined_results
│   │   │   └── resistance_summaries
│   │   ├── major_variants
│   │   │   └── results
│   │   ├── minor_variants
│   │   │   └── results
│   │   └── structural_variants
│   │       └── results
│   ├── phylogeny
│   └── snp_distances
└── vcf_files
    ├── cohort
    │   ├── combined_variant_files
    │   ├── minor_variants
    │   │   └── combined_variant_files
    │   ├── multiple_alignment_files
    │   ├── raw_variant_files
    │   ├── snp_variant_files
    │   │   ├── vqsr
    │   │   │   └── best_annotations
    │   │   │       └── best_annotation_files
    │   │   ├── vqsr__ann2
    │   │   ├── vqsr__ann3
    │   │   ├── vqsr__ann4
    │   │   ├── vqsr__ann5
    │   │   ├── vqsr__ann6
    │   │   └── vqsr__ann7
    │   └── structural_variants
    │       └── combined_variant_files
    └── per_sample
        ├── minor_variants
        ├── raw_variant_files
        └── structural_variants
            ├── delly
            └── tbprofiler

```

**Comment by TimHHH** [comment]
Do we have a run on biomina with this version's outputs? I see some things that can potentially be improved, but I need to double check the contents of the dirs.

**Comment by abhi18av** [comment]
@TimHHH , actually we're in touch with Tycho regarding the setup of docker-compatible node on the new SLURM cluster.

But let me share a proper tree (default for future runs) here for your convenience - please feel free to share your feedback here. 

```
.
├── QC_statistics
│   ├── cohort
│   │   ├── joint.cohort_stats.tsv
│   │   ├── joint.merged_cohort_stats.tsv
│   │   └── multiqc
│   │       ├── multiqc_data
│   │       │   ├── multiqc.log
│   │       │   ├── multiqc_data.json
│   │       │   ├── multiqc_fastqc.txt
│   │       │   ├── multiqc_general_stats.txt
│   │       │   └── multiqc_sources.txt
│   │       └── multiqc_report.html
│   └── per_sample
│       ├── coverage
│       │   ├── SMARTT_SOC.FD-002-FU-W5-M1-P.WgsMetrics.txt
│       │   └── SMARTT_SOC.FD-004-FU-W2-M1-P.WgsMetrics.txt
│       ├── fastqc
│       │   ├── FD002FUW5M1P_1_fastqc.html
│       │   ├── FD002FUW5M1P_1_fastqc.zip
│       │   ├── FD002FUW5M1P_2_fastqc.html
│       │   ├── FD002FUW5M1P_2_fastqc.zip
│       │   ├── FD004FUW2M1P_1_fastqc.html
│       │   ├── FD004FUW2M1P_1_fastqc.zip
│       │   ├── FD004FUW2M1P_2_fastqc.html
│       │   └── FD004FUW2M1P_2_fastqc.zip
│       └── mapping
│           ├── SMARTT_SOC.FD-002-FU-W5-M1-P.FlagStat.txt
│           ├── SMARTT_SOC.FD-002-FU-W5-M1-P.SamtoolStats.txt
│           ├── SMARTT_SOC.FD-004-FU-W2-M1-P.FlagStat.txt
│           └── SMARTT_SOC.FD-004-FU-W2-M1-P.SamtoolStats.txt
├── analyses
│   ├── cluster_analysis
│   │   ├── joint.ExDR.ExComplex.12SNPcluster.treefile
│   │   ├── joint.ExDR.ExComplex.5SNPcluster.treefile
│   │   ├── joint.ExDR.ExComplex_12SNPclusterPicks.nwk
│   │   ├── joint.ExDR.ExComplex_12SNPclusterPicks.nwk.figTree
│   │   ├── joint.ExDR.ExComplex_12SNPclusterPicks_log.txt
│   │   ├── joint.ExDR.ExComplex_5SNPclusterPicks.nwk
│   │   ├── joint.ExDR.ExComplex_5SNPclusterPicks.nwk.figTree
│   │   ├── joint.ExDR.ExComplex_5SNPclusterPicks_log.txt
│   │   ├── joint.variable.ExDR.ExComplex.12SNPcluster.fa
│   │   ├── joint.variable.ExDR.ExComplex.5SNPcluster.fa
│   │   ├── joint.variable.ExDR.ExComplex.fa_joint.ExDR.ExComplex_12SNPclusterPicks.fas
│   │   └── joint.variable.ExDR.ExComplex.fa_joint.ExDR.ExComplex_5SNPclusterPicks.fas
│   ├── drug_resistance
│   │   ├── combined_resistance_summaries
│   │   │   ├── MTb_L1.SAMN10185847.xlsx
│   │   │   ├── MTb_L2.SAMEA1877219.xlsx
│   │   │   ├── MTb_L3.SAMEA1877181.xlsx
│   │   │   ├── MTb_L410.ERR216945.xlsx
│   │   │   ├── MTb_L43.ERR1193883.xlsx
│   │   │   ├── MTb_L5.SAMEA1877169.xlsx
│   │   │   ├── MTb_L6.SAMEA1877150.xlsx
│   │   │   ├── MTb_L7.ERR1971849.xlsx
│   │   │   ├── MTb_L8.SRR10828835.xlsx
│   │   │   ├── MTb_L9.ERR4162024.xlsx
│   │   │   ├── Mcanettii.ERR5104570.xlsx
│   │   │   ├── SMARTT_SOC.FD-002-FU-W5-M1-P.xlsx
│   │   │   └── SMARTT_SOC.FD-004-FU-W2-M1-P.xlsx
│   │   ├── major_variants
│   │   │   ├── joint.major_variants.dr.indiv.itol.txt
│   │   │   ├── joint.major_variants.dr.itol.txt
│   │   │   ├── joint.major_variants.json
│   │   │   ├── joint.major_variants.lineage.itol.txt
│   │   │   ├── joint.major_variants.txt
│   │   │   ├── joint.major_variants.variants.txt
│   │   │   └── results
│   │   │       ├── MTb_L1.SAMN10185847.results.json
│   │   │       ├── MTb_L2.SAMEA1877219.results.json
│   │   │       ├── MTb_L3.SAMEA1877181.results.json
│   │   │       ├── MTb_L410.ERR216945.results.json
│   │   │       ├── MTb_L43.ERR1193883.results.json
│   │   │       ├── MTb_L5.SAMEA1877169.results.json
│   │   │       ├── MTb_L6.SAMEA1877150.results.json
│   │   │       ├── MTb_L7.ERR1971849.results.json
│   │   │       ├── MTb_L8.SRR10828835.results.json
│   │   │       ├── MTb_L9.ERR4162024.results.json
│   │   │       ├── Mcanettii.ERR5104570.results.json
│   │   │       ├── SMARTT_SOC.FD-002-FU-W5-M1-P.results.json
│   │   │       └── SMARTT_SOC.FD-004-FU-W2-M1-P.results.json
│   │   ├── minor_variants
│   │   │   ├── joint.minor_variants.dr.indiv.itol.txt
│   │   │   ├── joint.minor_variants.dr.itol.txt
│   │   │   ├── joint.minor_variants.json
│   │   │   ├── joint.minor_variants.lineage.itol.txt
│   │   │   ├── joint.minor_variants.txt
│   │   │   ├── joint.minor_variants.variants.txt
│   │   │   └── results
│   │   │       ├── SMARTT_SOC.FD-002-FU-W5-M1-P.results.json
│   │   │       └── SMARTT_SOC.FD-004-FU-W2-M1-P.results.json
│   │   └── structural_variants
│   │       ├── joint.structural_variants.dr.indiv.itol.txt
│   │       ├── joint.structural_variants.dr.itol.txt
│   │       ├── joint.structural_variants.json
│   │       ├── joint.structural_variants.lineage.itol.txt
│   │       ├── joint.structural_variants.txt
│   │       ├── joint.structural_variants.variants.txt
│   │       └── results
│   │           ├── SMARTT_SOC.FD-002-FU-W5-M1-P.results.json
│   │           └── SMARTT_SOC.FD-004-FU-W2-M1-P.results.json
│   ├── phylogeny
│   │   ├── joint.ExDR.ExComplex.bionj
│   │   ├── joint.ExDR.ExComplex.ckp.gz
│   │   ├── joint.ExDR.ExComplex.iqtree
│   │   ├── joint.ExDR.ExComplex.log
│   │   ├── joint.ExDR.ExComplex.mldist
│   │   ├── joint.ExDR.ExComplex.model.gz
│   │   └── joint.ExDR.ExComplex.treefile
│   └── snp_distances
│       └── joint.ExDR.ExComplex.snp_dists.tsv
└── vcf_files
    ├── cohort
    │   ├── combined_variant_files
    │   │   ├── joint.filtered_SNP.RawIndels.vcf.gz
    │   │   └── joint.filtered_SNP.RawIndels.vcf.gz.tbi
    │   ├── minor_variants
    │   │   └── combined_variant_files
    │   │       ├── joint.lofreq.vcf.gz
    │   │       └── joint.lofreq.vcf.gz.csi
    │   ├── multiple_alignment_files
    │   │   └── joint.variable.ExDR.ExComplex.fa
    │   ├── raw_variant_files
    │   │   ├── joint.raw_variants.annotated.vcf
    │   │   ├── joint.raw_variants.annotated.vcf.gz
    │   │   └── joint.raw_variants.annotated.vcf.gz.tbi
    │   ├── snp_variant_files
    │   │   ├── joint.filtered_SNP_exc-rRNA.vcf.gz
    │   │   ├── joint.filtered_SNP_exc-rRNA.vcf.gz.tbi
    │   │   ├── joint.filtered_SNP_inc-rRNA.vcf.gz
    │   │   ├── joint.filtered_SNP_inc-rRNA.vcf.gz.tbi
    │   │   ├── vqsr
    │   │   │   └── best_annotations
    │   │   │       ├── all_annotations_data.json
    │   │   │       └── best_annotation_files
    │   │   │           ├── joint.SNP.ANN2.recal.vcf.gz
    │   │   │           ├── joint.SNP.ANN2.recal.vcf.gz.tbi
    │   │   │           └── joint.SNP.ANN2.tranches
    │   │   ├── vqsr__ann2
    │   │   │   ├── joint.SNP.ANN2.R
    │   │   │   ├── joint.SNP.ANN2.R.pdf
    │   │   │   ├── joint.SNP.ANN2.annotations.txt
    │   │   │   ├── joint.SNP.ANN2.annotations_tranches.json
    │   │   │   ├── joint.SNP.ANN2.command.log
    │   │   │   ├── joint.SNP.ANN2.model
    │   │   │   ├── joint.SNP.ANN2.recal.vcf.gz
    │   │   │   ├── joint.SNP.ANN2.recal.vcf.gz.tbi
    │   │   │   ├── joint.SNP.ANN2.tranches
    │   │   │   └── joint.SNP.ANN2.tranches.pdf
    │   │   ├── vqsr__ann3
    │   │   │   ├── joint.SNP.ANN3.R
    │   │   │   ├── joint.SNP.ANN3.R.pdf
    │   │   │   ├── joint.SNP.ANN3.annotations.txt
    │   │   │   ├── joint.SNP.ANN3.annotations_tranches.json
    │   │   │   ├── joint.SNP.ANN3.command.log
    │   │   │   ├── joint.SNP.ANN3.model
    │   │   │   ├── joint.SNP.ANN3.recal.vcf.gz
    │   │   │   ├── joint.SNP.ANN3.recal.vcf.gz.tbi
    │   │   │   ├── joint.SNP.ANN3.tranches
    │   │   │   └── joint.SNP.ANN3.tranches.pdf
    │   │   ├── vqsr__ann4
    │   │   │   ├── joint.SNP.ANN4.R
    │   │   │   ├── joint.SNP.ANN4.R.pdf
    │   │   │   ├── joint.SNP.ANN4.annotations.txt
    │   │   │   ├── joint.SNP.ANN4.annotations_tranches.json
    │   │   │   ├── joint.SNP.ANN4.command.log
    │   │   │   ├── joint.SNP.ANN4.model
    │   │   │   ├── joint.SNP.ANN4.recal.vcf.gz
    │   │   │   ├── joint.SNP.ANN4.recal.vcf.gz.tbi
    │   │   │   ├── joint.SNP.ANN4.tranches
    │   │   │   └── joint.SNP.ANN4.tranches.pdf
    │   │   ├── vqsr__ann5
    │   │   │   ├── joint.SNP.ANN5.R
    │   │   │   ├── joint.SNP.ANN5.R.pdf
    │   │   │   ├── joint.SNP.ANN5.annotations.txt
    │   │   │   ├── joint.SNP.ANN5.annotations_tranches.json
    │   │   │   ├── joint.SNP.ANN5.command.log
    │   │   │   ├── joint.SNP.ANN5.model
    │   │   │   ├── joint.SNP.ANN5.recal.vcf.gz
    │   │   │   ├── joint.SNP.ANN5.recal.vcf.gz.tbi
    │   │   │   ├── joint.SNP.ANN5.tranches
    │   │   │   └── joint.SNP.ANN5.tranches.pdf
    │   │   ├── vqsr__ann6
    │   │   │   ├── joint.SNP.ANN6.R
    │   │   │   ├── joint.SNP.ANN6.R.pdf
    │   │   │   ├── joint.SNP.ANN6.annotations.txt
    │   │   │   ├── joint.SNP.ANN6.annotations_tranches.json
    │   │   │   ├── joint.SNP.ANN6.command.log
    │   │   │   ├── joint.SNP.ANN6.model
    │   │   │   ├── joint.SNP.ANN6.recal.vcf.gz
    │   │   │   ├── joint.SNP.ANN6.recal.vcf.gz.tbi
    │   │   │   ├── joint.SNP.ANN6.tranches
    │   │   │   └── joint.SNP.ANN6.tranches.pdf
    │   │   └── vqsr__ann7
    │   │       ├── joint.SNP.ANN7.R
    │   │       ├── joint.SNP.ANN7.R.pdf
    │   │       ├── joint.SNP.ANN7.annotations.txt
    │   │       ├── joint.SNP.ANN7.annotations_tranches.json
    │   │       ├── joint.SNP.ANN7.command.log
    │   │       ├── joint.SNP.ANN7.model
    │   │       ├── joint.SNP.ANN7.recal.vcf.gz
    │   │       ├── joint.SNP.ANN7.recal.vcf.gz.tbi
    │   │       ├── joint.SNP.ANN7.tranches
    │   │       └── joint.SNP.ANN7.tranches.pdf
    │   └── structural_variants
    │       └── combined_variant_files
    │           ├── joint.delly.vcf.gz
    │           └── joint.delly.vcf.gz.csi
    └── per_sample
        ├── minor_variants
        │   ├── SMARTT_SOC.FD-002-FU-W5-M1-P.Filtered_AF.vcf
        │   ├── SMARTT_SOC.FD-002-FU-W5-M1-P.LoFreq.Reformat.vcf
        │   ├── SMARTT_SOC.FD-002-FU-W5-M1-P.LoFreq.Reformat.vcf.gz
        │   ├── SMARTT_SOC.FD-002-FU-W5-M1-P.LoFreq.Reformat.vcf.gz.tbi
        │   ├── SMARTT_SOC.FD-004-FU-W2-M1-P.Filtered_AF.vcf
        │   ├── SMARTT_SOC.FD-004-FU-W2-M1-P.LoFreq.Reformat.vcf
        │   ├── SMARTT_SOC.FD-004-FU-W2-M1-P.LoFreq.Reformat.vcf.gz
        │   └── SMARTT_SOC.FD-004-FU-W2-M1-P.LoFreq.Reformat.vcf.gz.tbi
        ├── raw_variant_files
        │   └── joint.raw_variants.annotated.vcf.gz
        └── structural_variants
            ├── delly
            │   ├── SMARTT_SOC.FD-002-FU-W5-M1-P.delly.bcf
            │   └── SMARTT_SOC.FD-004-FU-W2-M1-P.delly.bcf
            └── tbprofiler
                ├── SMARTT_SOC.FD-002-FU-W5-M1-P.filtered.delly.bcf.gz
                ├── SMARTT_SOC.FD-002-FU-W5-M1-P.filtered.delly.bcf.gz.csi
                ├── SMARTT_SOC.FD-004-FU-W2-M1-P.filtered.delly.bcf.gz
                └── SMARTT_SOC.FD-004-FU-W2-M1-P.filtered.delly.bcf.gz.csi


```

**Comment by abhi18av** [comment]
Awaiting @TimHHH feedback before merging this PR.

**Comment by TimHHH** [comment]
Alright, that looks good.
I just don't understand the presence of '''joint.raw_variants.annotated.vcf.gz''' in the '''per sample''' section. It is however correctly published in the '''cohort section'''. Assuming these two files are the same the one in the '''per sample''' section can be deleted.
Otherwise good to go 👍

**Comment by abhi18av** [comment]
Thanks Tim, I've accommodated your feedback and now merging this code to `develop` branch.

**Pull request merged**
