### PR TITLE
WHO database v2 and TB-profiler v6.x

### PR DESCRIPTION
**Pull request by mdediegofuertes**
Database changes in:

https://github.com/TORCH-Consortium/MAGMA/tree/master/resources/resistance_db_who 

to reflect the changes made in the 2nd version of the WHO Catalogue.

### CODE REVIEW

**Comment by vrennie** [comment]
HI @abhi18av, I think that it doesn't make sense to have an option to call another version than the latest version of the catalogue, it may be that a user is not aware of the most up-to-date version and accidentally opts for a data version

**Comment by TimHHH** [comment]
Yes, very rare that people will actually want to use an older version, no need to put it in the repo, just keep a backup copy sitting around somewhere offline maybe.

**Comment by vrennie** [comment]
Indeed, lets just put in in zenedo

**Comment by vrennie** [comment]
Yes indeed! @mdediegofuertes @abhi18av do I just pull the who_db_resistance and publish it on zenedo?

**Comment by abhi18av** [comment]
Yup, you'd just need to add this zipped file to the Zenodo database
 
[resistance_db_who_v1.zip](https://github.com/TORCH-Consortium/MAGMA/files/14559680/resistance_db_who_v1.zip)

**Comment by abhi18av** [comment]
Related 

https://github.com/jodyphelan/tbdb/issues/62 
https://github.com/jodyphelan/TBProfiler/issues/333

**Pull request merged**
